name: Style checks and test

on: [push]

jobs:
  run_tests:
    name: Style checks and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: make deps
      - name: Lint
        run: make check
      - name: Test
        run: make test